openapi: 3.0.0
info:
  title: Shop Hub Product Service
  version: 1.0.0
  description: |-
    - Semua waktu menggunakan format RFC3339 dan timezone UTC secara default
    - Pastikan baca deskripsi field pada setiap endpoint
servers:
  - url: "https://product-service-dev.yummyrp.com"

paths:
  /api/v1/products:
    post:
      operationId: CreateProduct
      summary: Create Product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductCreateRequest"
      responses:
        "200":
          description: Successfully created product
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GeneralResponseSuccessID"
        "400":
          $ref: "#/components/responses/ValidationError"
        "500":
          $ref: "#/components/responses/InternalServerError"
      tags:
        - Product

  /api/v1/categories:
    post:
      operationId: CreateProductCategory
      summary: Create Product Category
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductCategoryCreateRequest"
      responses:
        "200":
          description: Successfully created category
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GeneralResponseSuccessID"
        "400":
          $ref: "#/components/responses/ValidationError"
        "500":
          $ref: "#/components/responses/InternalServerError"
      tags:
        - Category

components:
  schemas:
    ProductCreateRequest:
      type: object
      properties:
        name:
          type: string
          example: "Product A"
          x-oapi-codegen-extra-tags:
            validate: "required,min=3,max=100"
        description:
          type: string
          example: "Deskripsi produk A"
          x-oapi-codegen-extra-tags:
            validate: "required"
        price:
          type: number
          format: double
          example: 199000.00
          x-oapi-codegen-extra-tags:
            validate: "required,gt=0"
        stock:
          type: integer
          format: int64
          example: 100
          x-oapi-codegen-extra-tags:
            validate: "required,gte=0"
        sku:
          type: string
          example: "SKU-001"
          x-oapi-codegen-extra-tags:
            validate: "required,min=3,max=50"
        is_active:
          type: boolean
          example: true
        category_id:
          type: integer
          format: int64
          example: 1
      required:
        - name
        - description
        - price
        - stock
        - sku
        - is_active
        - category_id

    ProductCategoryCreateRequest:
      type: object
      properties:
        name:
          type: string
          example: "Elektronik"
          x-oapi-codegen-extra-tags:
            validate: "required,min=3,max=100"
        description:
          type: string
          example: "Kategori produk elektronik"
      required:
        - name
        - description

    GeneralResponseSuccessID:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 101
      required:
        - id

    GeneralErrorResponse:
      type: object
      properties:
        message:
          type: string
          example: "Validation failed"
        error_validations:
          type: array
          items:
            type: object
            properties:
              field:
                type: string
                example: "name"
              message:
                type: array
                items:
                  type: string
                example:
                  - Name is required
            required:
              - field
              - message
      required:
        - message

  responses:
    ValidationError:
      description: Validation failed
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/GeneralErrorResponse"
    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/GeneralErrorResponse"

  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
