CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  price NUMERIC(12,2) NOT NULL,
  stock INT NOT NULL,
  sku VARCHAR(100) NOT NULL,
  is_active BOOLEAN DEFAULT true NOT NULL,
  category_id BIGINT REFERENCES product_categories(id),
  trace_parent VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT now() NOT NULL,
  updated_at TIMESTAMP DEFAULT now() NOT NULL
);
